#!/bin/sh

rm -rf worklib
mkdir worklib

ncvlog -ams vco.vams -messages
ncvlog -ams testbench.vams -messages
ncvlog freq_meas.v -messages

ncelab testbench -timescale 10ps/1ps -messages

ncsim testbench -messages -analogcontrol run.scs -input run.tcl

rm *.log
