#!/bin/sh

rm -rf worklib
mkdir worklib

ncvlog -ams dac.vams -messages
ncvlog -ams testbench.vams -messages

ncelab testbench -timescale 10ps/1ps -messages

ncsim testbench -messages -gui & 

rm *.log
