[package]
name = "piperine-api"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
num-complex.workspace = true
ndarray.workspace = true
piperine-lang = { path = "../piperine-lang" }
piperine-codegen = { path = "../piperine-codegen" }
piperine-solver = { path = "../piperine-solver" }
