#!/bin/sh

rm -rf worklib
mkdir worklib
rm -rf my_connectlib 
mkdir my_connectlib 

# compiling the connect module and the connect rules
ncvlog -ams -work my_connectlib a2d.vams
ncvlog -ams -work my_connectlib connectrules.vams

ncvlog counter.v -messages
ncvlog -ams testbench.vams -messages

ncelab testbench my_connectrules -discipline logic -timescale 10ps/1ps -messages -iereport

ncsim testbench -messages -analogcontrol run.scs -input run.tcl

rm *.log
