name: IDE Extension CI

on:
  push:
    branches:
      - main
    paths:
      - 'editors/vscode/**'
      - '.github/workflows/ide.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'editors/vscode/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: editors/vscode

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: 'editors/vscode/package-lock.json'

    - name: Install Dependencies
      run: npm ci

    - name: Package Extension
      run: npx vsce package

    - name: Upload VSIX Artifact
      uses: actions/upload-artifact@v4
      with:
        name: piperine-vscode-extension
        path: editors/vscode/*.vsix
